### ISSUE TITLE
red grass

### ISSUE THREAD

**Issue by 6LuLu6** [apokryphus/eternal-hunt#1]
![изображение_2023-10-22_134441337](https://github.com/apokryphus/eternal-hunt/assets/148670036/ee936751-103d-4cae-b2d9-2e82b80b962e)
red grass is everywhere, the usual green grass has partially disappeared, it's very unpleasant for the eyes, but I want to use the mod

**Comment by apokryphus** [comment]
Have you tried, I dunno, looking in your mods folder for a folder called `mod_EH_Red_Grass` and consider what it does?
