### ISSUE TITLE
Humble suggestions, improvements. 

### ISSUE THREAD

**Issue by Handsomepretty** [apokryphus/eternal-hunt#2]
Health. How are you doing? 
Good job with the mod, but maybe if Eternal Hunt had it's own settings for Geralt Combat Speed(light attack speed, strong attack speed, whirl speed, rend speed, dodge speed, roll speed), creatures enemy overall speed. And also maybe option to disable EH's blood and gore.
And also sometimes Geralt will just stand still and nothing but load save will help.
P.S. What´s the purpose of red grass?
Just a suggestions. Good luck. No offense.

**Comment by apokryphus** [comment]
No offense taken at all. The red grass serves no purpose other than to look visually different from vanilla.

> And also sometimes Geralt will just stand still and nothing but load save will help.
I'll need to look into this and find a way to reproduce it.

> And also maybe option to disable EH's blood and gore.
Most likely not going to happen.

> if Eternal Hunt had it's own settings for Geralt Combat Speed(light attack speed, strong attack speed, whirl speed, rend speed, dodge speed, roll speed), creatures enemy overall speed. 
A lot of the animation speeds are fixed for balance purposes with the rest of the mod. I'll think about making options for this but it probably won't be worked on in the near future.

**Comment by Handsomepretty** [comment]
> > And also sometimes Geralt will just stand still and nothing but load save will help.
> 
> I'll need to look into this and find a way to reproduce it.

Seems like it doesn't happen anymore after 1.16 release. Currently using 1.18 release. IIRC it happened to me using Olgierd style. Maybe some settings was causing it. IDK. But now seems good.



> > And also maybe option to disable EH's blood and gore.
> 
> Most likely not going to happen.

Please. It's kinda makes sense but a lot of blood spilling in the exact time when hitting causing lags, -fps. It's very noticeable when you use whirl.

 

> > if Eternal Hunt had it's own settings for Geralt Combat Speed(light attack speed, strong attack speed, whirl speed, rend speed, dodge speed, roll speed), creatures enemy overall speed.
> 
> A lot of the animation speeds are fixed for balance purposes with the rest of the mod. I'll think about making options for this but it probably won't be worked on in the near future

It would be very fitting for a Vampire Claws (faster attacks, faster walking, faster dodges, faster teleport dodge), run speed is already good with faster sprinting speed mod, and also while using Vampire Claws when sprinting he transforms into red mist and it has it's own insane speed or it's Faster Sprinting mod speed IDK but anyway Sprint Speed is good since other mod modifies it for all styles and it's compatible. But for example Combat Speed mod modifies only Geralt's default moveset (light attacks, strong attacks, dodges, whirl, rend, rolls,). So it would be very good having aslo combat speed settings only for Vampire Style and Olgierd Style(Cause they are the coolest and kinda makes sense for Vampire, for Olgierd style as bonus maybe).

Thanks. Just my experience from using this cool mod and just a suggestions to improve it. No offense. No demands. Good luck in everything. Good health to you.

**Comment by Handsomepretty** [comment]
Hola. Thanks for reducing blood and gore in your mod. Performance wise seems much better though I disabled a lot of stuff that caused lags, so yeah. Also very curious any chance to add fledder jump attack and jump back in vampire claws, maybe instead of underwhelming WW in vampire claws and that vomit attack W+parry button which is also in vampire claws or just add new inputs? 
Merry Christmas, Happy Holidays! Wish you eternal health!

**Comment by Handsomepretty** [comment]
Hi! Happy New Year! Good health to you! Good luck with everything! I fell bad that I can't support you so if you need help with anything just ask I'll try to help.
If it's easy can you please add toggle to remove vampire claws in vampire style like in No Wolverine Claws mod? (I tried to give that mod priority but it didn't overwrite vampire claws while in vampire style)
And please can you please make so when evolving weapons is turned off sword claws would change to bloody vampire claws?
And last humble request to add fledder/garkain knockdown jump attack and jump back to vampire style move set please?
Thanks for the mod. I am very sorry for my insolence. Good physical and mental health to you and good luck with everything!
