### ISSUE TITLE
V1.42  Monsters Spawns Issue

### ISSUE THREAD

**Issue by 0jit0** [apokryphus/eternal-hunt#6]
Monster Spawns issue: happened so far with the assassins and now with a Rotfiend Nest, simply cannot damage the enemy or at least in a way that the health bar moves, i was able to damage the assassin and the bar actually moves but with max adrenaline by using the bruxa bite (not able to damage with sword, magic spells mod movements or regular signs)

I get the notification prompts for damage tho, Between 80 to 120 silver for rotfiend steel for assassins but still the bar wont move. 

As for the Rotfiend Nest,  spawn rate for little ones is out of hand, there are simply too many and without a build designed to lower damage received by them exploding is impossible to beat in a new playtrough, maybe there should be some scaling. I beated a similar enemy  ''Xeno Swarm'' but in my New Game + with many skills and right equipment (also spawn rate a little excessive, is not hard with the right equipment, just annoying).  Even without the health bar issue i'm guessing Rotfiend Nest is unbeatable without having north of 25 Skill points and some extra damage reduction from armor (like bear set).

Would you recommend to disable some encounters depending on skill tree level each player is currently on?  Would it be possible to segment the enemies based on the real possibility of defeating them according to Geralt's level? Again, is not just hardcore playtrough, lower than Level 20-25 and armor that reduces the damage of exploding  small rotfiends no one is beating that nest as it is. 

Impossible to lock target on the big Rotfiend, targeting keeps jumping out even in manual, but since this makes it more difficult maybe is intentional. Not exactly a fan of this since some of the EH and Magic Spells moves requires the lock but please let me know if this is also intentional. 

Will report about another encounters as i find them.

**Comment by 0jit0** [comment]
Yeah, there's definitely a scaling problem here, besides the spawning rate in Rotfiends and Xenos, just spent the last 30 mins fighting an Incubus, is the fight that never ends is too easy to dodge him and can hit him max 3 times without swirl while Geralt is low level. 30 mins for lowering half of the first segment of life.

**Comment by 0jit0** [comment]
Nekker Guardian and Incubus keeps respawning after killing them near the location where the Keira Metz quest starts. can't complete the quest without turning the encounters off .

**Comment by 0jit0** [comment]
![Captura de pantalla 2023-12-17 163242](https://github.com/apokryphus/eternal-hunt/assets/129215463/b0f293a4-605b-45b7-8f87-1c271f996f66)

Any way to disable the quest tracking in the hud? Would be nice to have a menu toggle for it

**Comment by apokryphus** [comment]
Turn the spawning delay for markers to 0 in HUD settings. 

There's also a reason why some encounters are optional, like the necrofiend nests. They require the player to deal a significant amount of damage to them, or play strategically.

I'm more active on discord btw. If you have more questions it's better to contact me there.

https://discord.com/invite/KEjb533Fr6

**Comment by 0jit0** [comment]
Just joined the discord👍 thanks again for the help and fast response, sorry for my annoyance
