### ISSUE TITLE
Enhancement ideas. New features or requests.

### ISSUE THREAD

**Issue by Handsomepretty** [apokryphus/eternal-hunt#7]
Hi! Happy New Year! Good health to you! Good luck with everything! I feel bad that I can't support you so if you need help with anything just ask, I'll try to help.
Here is the idea about Khagmar. How about to create Khagmar human form and enhance him so he would have all Detlaff/Regis, Bruxa dash, whole Bruxa moveset and Fledder's/Garkain's jump attack, jump retreat etc, summon bats attack that would heal him all the cool stuff. And maybe add him to Bruxa lovers. How about maybe even change Bruxa killing consequences: 1st time after killing Bruxas, Blade of the Unseen, 1 Bruxae and 1 Mula shows up. 2nd time Blade of the Unseen and 1 Mula, 1 Bruxae, 1 Alp. And 3rd time here he comes Khagmar human form and Night Hunter after defeating Khagmar he transforms into Khagmar, Monster of the Unseen. Be afraid. Be very afraid. What you think?
Also how about adding whole van Moorlehem higher vampire family; 3 Higher Vampires and their human goons?
About aesthetics, no offense but Blade of the Unseen looks kinda unfinished too, his blades texture clips with his hands so it looks kinda bad, sorry. Maybe give him at least bloody sword claws and place them a little bit further from his hands to minimize clipping. And his face looks unfinished. Maybe dress him up in full Hen Gaidth and Tesham Mutna armor sets.
But Khagmar, Monster of the Unseen looks cool, his bloody parts and head distinguish him from Detlaff's monster form. From what I remember Higher Vampire monster forms are different from eachother, for example Regis' monster form looks like Man-Bat from DC. But unfortunately CDPR only gave us Detlaff's monster form. And suggestion to improve Khagmar, Monster of the Unseen and player's monster vampire form are to just make him move a lot faster cause he moves very slow. 

Sorry for making another issue and for such big post but I just wanted to explain good enough so yeah.
Thanks for the mod. I am very sorry. Good physical and mental health to you and good luck with everything!

**Comment by 3nz0p1l0** [comment]
Well, i also gonna hop in in the request part and ask that all the changes on movement, talking about changes made to scripts explorationStateJump/Slide be modular, i find quite strange geralds behavior, don't no why tho, but when i remove those file everything goes back to normal. 

Another thing i also wanted to disable but the mod doens't have a option for that is to disable the Aard Explosion when you fall from a high place, i don't see myself using it.

Thats all, thanks for making a great mod and be well !
